version: 2.1

jobs:
  build:
    docker:
      - image: gamecss/lollipop_buildenv:latest
    resource_class: large
    steps:
      - run:
          name: Get source
          command: |
            echo 'JACK_SERVER_VM_ARGUMENTS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4096m"' > ~/.jack-settings   
            mkdir aosp
            cd aosp
            pwd
            df -h
            git config --global user.email "116288337+xunmod@users.noreply.github.com"
            git config --global user.name "xunmod@bot"
            sudo rm -f /usr/bin/python
            sudo ln -sf /usr/local/bin/python3.8 /usr/bin/python
            repo init --depth=1 -u https://github.com/pine64-android/manifest -b master
            repo sync -c -f --no-tags --no-clone-bundle -j16
            git clone --single-branch -b lollipop --depth 1 https://github.com/xunmod/android_device_ONDA_octopus-ibt device/ONDA/octopus-ibt
            git clone --single-branch -b lollipop --depth 1 https://github.com/xunmod/external_chromium-webview external/chromium-webview
            rm -rf .repo/project-objects
            rm -r device/softwinner/octopus-ibt
            cd device/ONDA/octopus-ibt
            patch -p1 < prebuilt_webview.patch
            cd ../../..
      - run:
          name: Build
          command: |
            export LC_ALL=C
            export _JAVA_OPTIONS="-Xmx4096m"
            sudo rm -f /usr/bin/python
            sudo ln -sf /usr/bin/python2.7 /usr/bin/python
            cd aosp
            source build/envsetup.sh
            lunch octopus_ibt-userdebug
            mm -j16
            tar -czvf images.tar.gz $(find out/target/product/octopus-ibt -name *.img | xargs) $(find out/target/product/octopus_ibt -name *.img | xargs) $(find out/target/product/octopus-ibt -name *.fex | xargs) $(find out/target/product/octopus_ibt -name *.fex | xargs)

      - store_artifacts:
          path: /root/project/aosp/images.tar.gz
