version: 2.1

jobs:
  build:
    docker:
      - image: gamecss/lollipop_buildenv:latest
    resource_class: large
    steps:
      - run:
          name: Get source
          command: |
            echo 'JACK_SERVER_VM_ARGUMENTS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx5120m"' > ~/.jack-settings   
            mkdir aosp
            cd aosp
            git config --global user.email "116288337+xunmod@users.noreply.github.com"
            git config --global user.name "xunmod@bot"
            sudo rm -f /usr/bin/python
            sudo ln -sf /usr/local/bin/python3.8 /usr/bin/python
            repo init --depth=1 -u https://github.com/xunmod/android_manifest -b a64
            repo sync -c -f --no-tags --no-clone-bundle -j32
            git clone --single-branch -b lollipop --depth 1 https://github.com/xunmod/android_device_ONDA_octopus-ibt device/ONDA/octopus-ibt
            git clone --single-branch -b lollipop --depth 1 https://github.com/xunmod/external_chromium-webview external/chromium-webview
            rm -rf .repo/project-objects
            rm -r device/softwinner/octopus-ibt
            patch -p1 < device/ONDA/octopus-ibt/prebuilt_webview.patch
            cd system/core && curl https://github.com/LineageOS/android_system_core/commit/75ac84c0bf57d646dfae468916fcdcc071570293.patch | patch -p1 - && cd ../..
            cd frameworks/av && curl https://github.com/LineageOS/android_frameworks_av/commit/5a6788730acfc6fd8f4a6ef89d2c376572a26b55.patch | patch -p1 - && cd ../..
      - run:
          name: Build
          command: |
            export LC_ALL=C
            export _JAVA_OPTIONS="-Xmx5120m"
            sudo rm -f /usr/bin/python
            sudo ln -sf /usr/bin/python2.7 /usr/bin/python
            cd aosp
            source build/envsetup.sh
            lunch octopus_ibt-userdebug
            mm -j32
            tar -czvf images.tar.gz $(find out/target/product/octopus-ibt -name *.img | xargs) $(find out/target/product/octopus_ibt -name *.img | xargs) $(find out/target/product/octopus-ibt -name *.fex | xargs) $(find out/target/product/octopus_ibt -name *.fex | xargs)

      - store_artifacts:
          path: /root/project/aosp/images.tar.gz
