name: Compile AOSP 5.1
on:
  push:
    branches: [ "lollipop" ]
  workflow_dispatch:
    inputs:
      enable_ssh:
        description: 'enable ssh or not'
        required: true
        type: boolean
        default: false
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gamecss/lollipop_buildenv:latest
    env:
      LC_ALL: "C"
    steps:
      - name: Get disk usage
        run: |
          echo "==========  /  =========="
          sudo du -hxd3 /
          echo "========== __* =========="
          sudo du -hxd2 /__*
          echo "==========wrkpl=========="
          sudo du -hxd2 /workplaces || true
          df -h
      - name: Get source
        run: |
          mkdir $GITHUB_WORKSPACE/aosp
          cd $GITHUB_WORKSPACE/aosp
          git config --global user.email "116288337+xunmod@users.noreply.github.com"
          git config --global user.name "xunmod@bot"
          sudo rm -f /usr/bin/python
          sudo ln -sf /usr/local/bin/python3.8 /usr/bin/python
          repo init --depth=1 -u https://github.com/xunmod/android_manifest -b lollipop
          mkdir .repo/local_manifests
          wget https://github.com/xunmod/android_device_ONDA_octopus-ibt/raw/lollipop/.github/extras.xml -O .repo/local_manifests/extras.xml
          repo sync -c -f --no-tags --no-clone-bundle -j16
          rm -r device/softwinner/octopus-ibt
          curl https://github.com/xunmod/twrp_device_ONDA_octopus-ibt/raw/twrp-4.4/twrp_gdb.patch | patch -p1 -
          mv bootable/recovery-cm/applydiff bootable/recovery/
          rm -rf bootable/recovery-cm
      - name: Build
        shell: bash
        run: |
          sudo rm -f /usr/bin/python
          sudo ln -sf /usr/bin/python2.7 /usr/bin/python
          cd $GITHUB_WORKSPACE/aosp
          source build/envsetup.sh
          lunch octopus_ibt-userdebug
          make -j$(nproc --all)
      - name: Package image
        run: |
          tar -czvf images.tar.gz $(find aosp/out/target/product/octopus-ibt -name *.img | xargs)
      - uses: actions/upload-artifact@v3
        with:
          name: Images
          path: 'images.tar.gz'
      - name: Setup tmate session
        if: ${{ failure() || inputs.enable_ssh }}
        run: |
          wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz
          tar -tf tmate-2.4.0-static-linux-amd64.tar.xz
          sudo mv tmate*/tmate /usr/bin
          sudo chown +x /usr/bin/tmate
          tmate
          cat << EOF >> tmate_keeper
          while true
          do
          sleep 1800
          done
          EOF
          chmod +x tmate_keeper
          ./tmate_keeper
