name: Compile AOSP 5.1
on:
  push:
    branches: [ "lollipop" ]
  workflow_dispatch:
    inputs:
      enable_ssh:
        description: 'enable ssh or not'
        required: true
        type: boolean
        default: false
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gamecss/lollipop_buildenv:latest
    env:
      LC_ALL: "C"
    steps:
      - name: Get source
        run: |
          mkdir $GITHUB_WORKSPACE/aosp
          cd $GITHUB_WORKSPACE/aosp
          git config --global user.email "116288337+xunmod@users.noreply.github.com"
          git config --global user.name "xunmod@bot"
          sudo rm -f /usr/bin/python
          sudo ln -sf /usr/local/bin/python3.8 /usr/bin/python
          repo init --depth=1 -u https://github.com/xunmod/android_manifest -b lollipop
          repo sync -c -f --no-tags --no-clone-bundle -j16
          rm -r device/softwinner/octopus-ibt
          git clone --single-branch -b lollipop --depth 1 https://github.com/xunmod/android_device_ONDA_octopus-ibt device/ONDA/octopus-ibt
      - name: Build
        shell: bash
        run: |
          sudo rm -f /usr/bin/python
          sudo ln -sf /usr/bin/python2.7 /usr/bin/python
          cd $GITHUB_WORKSPACE/aosp
          source build/envsetup.sh
          lunch octopus_ibt-userdebug
          mka -j$(nproc --all)
      - name: Package image
        run: |
          tar -czvf images.tar.gz $(find aosp/out/target/product/octopus-ibt -name *.img | xargs)
      - uses: actions/upload-artifact@v3
        with:
          name: Images
          path: 'images.tar.gz'
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() || inputs.enable_ssh }}
        with:
          limit-access-to-actor: false
